apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: praktik
spec:
  replicas: 5
  selector:
    matchLabels:
      app: praktik-auth
  template:
    metadata:
      labels:
        app: praktik-auth
    spec:
      containers:
      - name: praktik-auth
        image: praktikut/praktik-auth:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: praktik-auth
spec:
  type: NodePort
  selector:
    app: praktik-auth
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
