apiVersion: v1
kind: Service
metadata:
  name: firebase-service
  labels:
    name: firebase-service
spec:
  type: ExternalName
  externalName: firebaseio.com
  ports:
    - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: gmail-service
  labels:
    name: gmail-service
spec:
  type: ExternalName
  externalName: gmail.com
  ports:
    - port: 587

---


apiVersion: v1
kind: Service
metadata:
  name: googleapisaccount-service
  labels:
    name: googleapisaccount-service
spec:
  type: ExternalName
  externalName: google.com
  ports:
    - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: oauthgoogle-service
  labels:
    name: oauthgoogle-service
spec:
  type: ExternalName
  externalName: googleapis.com
  ports:
    - port: 80

---
